module.exports = {
	MYSQL_DB: 'mysql://root:root@localhost:3306/mynode?debug=false&connectTimeout=4000&charset=UTF8_GENERAL_CI&timezone=+0000',
	EMAIL: {
		SERVER: 'QQ',
		USER: '362428028@qq.com',
		PASS: 'cssijvdxhzszcbda',
	}
};
//'1und1',
//'AOL',
//'DebugMail.io',
//'DynectEmail',
//'FastMail',
//'GandiMail',
//'Gmail',
//'Godaddy',
//'GodaddyAsia',
//'GodaddyEurope',
//'hot.ee',
//'Hotmail',
//'iCloud',
//'mail.ee',
//'Mail.ru',
//'Mailgun',
//'Mailjet',
//'Mandrill',
//'Naver',
//'OpenMailBox',
//'Postmark',
//'QQ',
//'QQex',
//'SendCloud',
//'SendGrid',
//'SES',
//'SES-US-EAST-1',
//'SES-US-WEST-1',
//'SES-EU-WEST-1',
//'Sparkpost',
//'Yahoo',
//'Yandex',
//'Zoho'
